% -------------------------------------------------------------------
%  Generated by MATLAB on 10-Sep-2025 21:35:00
%  MATLAB version: 9.11.0.1769968 (R2021b)
% -------------------------------------------------------------------
                                

EngineTWT_Enginerunhours = 10;

EngineTWT_EnginerunhoursState = 7;

EngineTWT_NVMengierLastToalTimes = Simulink.Signal;
EngineTWT_NVMengierLastToalTimes.CoderInfo.StorageClass = 'Auto';
EngineTWT_NVMengierLastToalTimes.Description = '';
EngineTWT_NVMengierLastToalTimes.DataType = 'auto';
EngineTWT_NVMengierLastToalTimes.Min = [];
EngineTWT_NVMengierLastToalTimes.Max = [];
EngineTWT_NVMengierLastToalTimes.DocUnits = '';
EngineTWT_NVMengierLastToalTimes.Dimensions = -1;
EngineTWT_NVMengierLastToalTimes.DimensionsMode = 'auto';
EngineTWT_NVMengierLastToalTimes.Complexity = 'auto';
EngineTWT_NVMengierLastToalTimes.SampleTime = -1;
EngineTWT_NVMengierLastToalTimes.InitialValue = '';

NVM_CFG_ENG_TYPE = 12;

NVM_HFV_Enginerunhours = 1;

REV_EngineSpeed = 6;

REV_EngineSpeedState = 5;

RXSIG_EngHrRev_Total_engine_hours = 13;

SIG_CLASS_COMTX = 8;

SIG_CLASS_NVM = 2;

SIG_CLASS_NVM_CFG = 3;

SIG_CLASS_SWC = 4;

TXSIG_EngHrRev_EGR_Total_engine_hours = 9;

TXSIG_HOURS_EGR_EngineTotalHoursofOperation = 11;

