/*===========================================================================*/
/* Module      = dr7f701373_irq.h                                            */
/* Version     = V1.21                                                       */
/*               extracted from device file dr7f701373.dvf                   */
/*               generated by DeFiXRH850 0.9.1.0                             */
/*===========================================================================*/
/*                                  COPYRIGHT                                */
/*===========================================================================*/
/* Copyright (c) 2017 by Renesas Electronics Europe GmbH,                    */
/*               a company of the Renesas Electronics Corporation            */
/*===========================================================================*/
/* Purpose:      Declarations of Interrupt Vector Table                      */
/*                                                                           */
/*===========================================================================*/
/*                                                                           */
/* Warranty Disclaimer                                                       */
/*                                                                           */
/* Because the Product(s) is licensed free of charge, there is no warranty   */
/* of any kind whatsoever and expressly disclaimed and excluded by Renesas,  */
/* either expressed or implied, including but not limited to those for       */
/* non-infringement of intellectual property, merchantability and/or         */
/* fitness for the particular purpose.                                       */
/* Renesas shall not have any obligation to maintain, service or provide bug */
/* fixes for the supplied Product(s) and/or the Application.                 */
/*                                                                           */
/* Each User is solely responsible for determining the appropriateness of    */
/* using the Product(s) and assumes all risks associated with its exercise   */
/* of rights under this Agreement, including, but not limited to the risks   */
/* and costs of program errors, compliance with applicable laws, damage to   */
/* or loss of data, programs or equipment, and unavailability or             */
/* interruption of operations.                                               */
/*                                                                           */
/* Limitation of Liability                                                   */
/*                                                                           */
/* In no event shall Renesas be liable to the User for any incidental,       */
/* consequential, indirect, or punitive damage (including but not limited    */
/* to lost profits) regardless of whether such liability is based on breach  */
/* of contract, tort, strict liability, breach of warranties, failure of     */
/* essential purpose or otherwise and even if advised of the possibility of  */
/* such damages. Renesas shall not be liable for any services or products    */
/* provided by third party vendors, developers or consultants identified or  */
/* referred to the User by Renesas in connection with the Product(s) and/or  */
/* the Application.                                                          */
/*                                                                           */
/*===========================================================================*/
/* Environment:                                                              */
/*              Device:         R7F701373xABG                                */
/*              IDE:            GHS Multi for V800  V6.xx or later           */
/*===========================================================================*/

#ifndef __R7F701373xABG_IRQ_H
#define __R7F701373xABG_IRQ_H

#define IRQ_TABLE_START                 0x00000600u

#define RESET_ENABLE                    0x00000001u

// #define SYSERR_ENABLE                   0x00000010u
#ifndef SYSERR_ENABLE                  
  #define SYSERR_ENABLE                   0x00000000u
#endif

// #define FETRAPEX_ENABLE                 0x00000030u
#ifndef FETRAPEX_ENABLE                
  #define FETRAPEX_ENABLE                 0x00000000u
#endif

// #define EITRAP0_ENABLE                  0x00000040u
#ifndef EITRAP0_ENABLE                 
  #define EITRAP0_ENABLE                  0x00000000u
#endif

// #define EITRAP1_ENABLE                  0x00000050u
#ifndef EITRAP1_ENABLE                 
  #define EITRAP1_ENABLE                  0x00000000u
#endif

// #define RIEX_ENABLE                     0x00000060u
#ifndef RIEX_ENABLE                    
  #define RIEX_ENABLE                     0x00000000u
#endif

// #define UCPOP_ENABLE                    0x00000080u
#ifndef UCPOP_ENABLE                   
  #define UCPOP_ENABLE                    0x00000000u
#endif

// #define MIP_MDP_ENABLE                  0x00000090u
#ifndef MIP_MDP_ENABLE                 
  #define MIP_MDP_ENABLE                  0x00000000u
#endif

// #define PIEX_ENABLE                     0x000000A0u
#ifndef PIEX_ENABLE                    
  #define PIEX_ENABLE                     0x00000000u
#endif

// #define MAEX_ENABLE                     0x000000C0u
#ifndef MAEX_ENABLE                    
  #define MAEX_ENABLE                     0x00000000u
#endif

// #define MAE_ENABLE                      0x000000C0u
#ifndef MAE_ENABLE                     
  #define MAE_ENABLE                      0x00000000u
#endif

// #define FENMI_ENABLE                    0x000000E0u
#ifndef FENMI_ENABLE                   
  #define FENMI_ENABLE                    0x00000000u
#endif

// #define FEINT_ENABLE                    0x000000F0u
#ifndef FEINT_ENABLE                   
  #define FEINT_ENABLE                    0x00000000u
#endif

// #define EINTPRIO_0_ENABLE               0x00000100u
#ifndef EINTPRIO_0_ENABLE              
  #define EINTPRIO_0_ENABLE               0x00000000u
#endif

// #define EINTPRIO_1_ENABLE               0x00000110u
#ifndef EINTPRIO_1_ENABLE              
  #define EINTPRIO_1_ENABLE               0x00000000u
#endif

// #define EINTPRIO_2_ENABLE               0x00000120u
#ifndef EINTPRIO_2_ENABLE              
  #define EINTPRIO_2_ENABLE               0x00000000u
#endif

// #define EINTPRIO_3_ENABLE               0x00000130u
#ifndef EINTPRIO_3_ENABLE              
  #define EINTPRIO_3_ENABLE               0x00000000u
#endif

// #define EINTPRIO_4_ENABLE               0x00000140u
#ifndef EINTPRIO_4_ENABLE              
  #define EINTPRIO_4_ENABLE               0x00000000u
#endif

// #define EINTPRIO_5_ENABLE               0x00000150u
#ifndef EINTPRIO_5_ENABLE              
  #define EINTPRIO_5_ENABLE               0x00000000u
#endif

// #define EINTPRIO_6_ENABLE               0x00000160u
#ifndef EINTPRIO_6_ENABLE              
  #define EINTPRIO_6_ENABLE               0x00000000u
#endif

// #define EINTPRIO_7_ENABLE               0x00000170u
#ifndef EINTPRIO_7_ENABLE              
  #define EINTPRIO_7_ENABLE               0x00000000u
#endif

// #define EINTPRIO_8_ENABLE               0x00000180u
#ifndef EINTPRIO_8_ENABLE              
  #define EINTPRIO_8_ENABLE               0x00000000u
#endif

// #define EINTPRIO_9_ENABLE               0x00000190u
#ifndef EINTPRIO_9_ENABLE              
  #define EINTPRIO_9_ENABLE               0x00000000u
#endif

// #define EINTPRIO_10_ENABLE              0x000001A0u
#ifndef EINTPRIO_10_ENABLE             
  #define EINTPRIO_10_ENABLE              0x00000000u
#endif

// #define EINTPRIO_11_ENABLE              0x000001B0u
#ifndef EINTPRIO_11_ENABLE             
  #define EINTPRIO_11_ENABLE              0x00000000u
#endif

// #define EINTPRIO_12_ENABLE              0x000001C0u
#ifndef EINTPRIO_12_ENABLE             
  #define EINTPRIO_12_ENABLE              0x00000000u
#endif

// #define EINTPRIO_13_ENABLE              0x000001D0u
#ifndef EINTPRIO_13_ENABLE             
  #define EINTPRIO_13_ENABLE              0x00000000u
#endif

// #define EINTPRIO_14_ENABLE              0x000001E0u
#ifndef EINTPRIO_14_ENABLE             
  #define EINTPRIO_14_ENABLE              0x00000000u
#endif

// #define EINTPRIO_15_ENABLE              0x000001F0u
#ifndef EINTPRIO_15_ENABLE             
  #define EINTPRIO_15_ENABLE              0x00000000u
#endif

// #define INTICUP1_ENABLE                (IRQ_TABLE_START + 0x00000000u)
#ifndef INTICUP1_ENABLE               
  #define INTICUP1_ENABLE                0x00000000u
#endif


// #define INTECM0MI_ENABLE                (IRQ_TABLE_START + 0x00000000u)
#ifndef INTECM0MI_ENABLE               
  #define INTECM0MI_ENABLE                0x00000000u
#endif

// #define INTBN0_ENABLE                   (IRQ_TABLE_START + 0x00000010u)
#ifndef INTBN0_ENABLE                  
  #define INTBN0_ENABLE                   0x00000000u
#endif

// #define INTBN1_ENABLE                   (IRQ_TABLE_START + 0x00000014u)
#ifndef INTBN1_ENABLE                  
  #define INTBN1_ENABLE                   0x00000000u
#endif

// #define INTBN2_ENABLE                   (IRQ_TABLE_START + 0x00000018u)
#ifndef INTBN2_ENABLE                  
  #define INTBN2_ENABLE                   0x00000000u
#endif

// #define INTBN3_ENABLE                   (IRQ_TABLE_START + 0x0000001Cu)
#ifndef INTBN3_ENABLE                  
  #define INTBN3_ENABLE                   0x00000000u
#endif

// #define INTWDTA0_ENABLE                 (IRQ_TABLE_START + 0x00000020u)
#ifndef INTWDTA0_ENABLE                
  #define INTWDTA0_ENABLE                 0x00000000u
#endif

// #define INTSW0_ENABLE                   (IRQ_TABLE_START + 0x00000024u)
#ifndef INTSW0_ENABLE                  
  #define INTSW0_ENABLE                   0x00000000u
#endif

// #define INTSW1_ENABLE                   (IRQ_TABLE_START + 0x00000028u)
#ifndef INTSW1_ENABLE                  
  #define INTSW1_ENABLE                   0x00000000u
#endif

// #define INTSW2_ENABLE                   (IRQ_TABLE_START + 0x0000002Cu)
#ifndef INTSW2_ENABLE                  
  #define INTSW2_ENABLE                   0x00000000u
#endif

// #define INTSTM02_ENABLE                 (IRQ_TABLE_START + 0x00000030u)
#ifndef INTSTM02_ENABLE                
  #define INTSTM02_ENABLE                 0x00000000u
#endif

// #define INTSTM03_ENABLE                 (IRQ_TABLE_START + 0x00000034u)
#ifndef INTSTM03_ENABLE                
  #define INTSTM03_ENABLE                 0x00000000u
#endif

// #define INTSTM04_ENABLE                 (IRQ_TABLE_START + 0x00000038u)
#ifndef INTSTM04_ENABLE                
  #define INTSTM04_ENABLE                 0x00000000u
#endif

// #define INTSTM05_ENABLE                 (IRQ_TABLE_START + 0x0000003Cu)
#ifndef INTSTM05_ENABLE                
  #define INTSTM05_ENABLE                 0x00000000u
#endif

// #define INTDMA0_ENABLE                  (IRQ_TABLE_START + 0x00000040u)
#ifndef INTDMA0_ENABLE                 
  #define INTDMA0_ENABLE                  0x00000000u
#endif

// #define INTDMA1_ENABLE                  (IRQ_TABLE_START + 0x00000044u)
#ifndef INTDMA1_ENABLE                 
  #define INTDMA1_ENABLE                  0x00000000u
#endif

// #define INTDMA2_ENABLE                  (IRQ_TABLE_START + 0x00000048u)
#ifndef INTDMA2_ENABLE                 
  #define INTDMA2_ENABLE                  0x00000000u
#endif

// #define INTDMA3_ENABLE                  (IRQ_TABLE_START + 0x0000004Cu)
#ifndef INTDMA3_ENABLE                 
  #define INTDMA3_ENABLE                  0x00000000u
#endif

// #define INTDMA4_ENABLE                  (IRQ_TABLE_START + 0x00000050u)
#ifndef INTDMA4_ENABLE                 
  #define INTDMA4_ENABLE                  0x00000000u
#endif

// #define INTDMA5_ENABLE                  (IRQ_TABLE_START + 0x00000054u)
#ifndef INTDMA5_ENABLE                 
  #define INTDMA5_ENABLE                  0x00000000u
#endif

// #define INTDMA6_ENABLE                  (IRQ_TABLE_START + 0x00000058u)
#ifndef INTDMA6_ENABLE                 
  #define INTDMA6_ENABLE                  0x00000000u
#endif

// #define INTDMA7_ENABLE                  (IRQ_TABLE_START + 0x0000005Cu)
#ifndef INTDMA7_ENABLE                 
  #define INTDMA7_ENABLE                  0x00000000u
#endif

// #define INTDMA8_ENABLE                  (IRQ_TABLE_START + 0x00000060u)
#ifndef INTDMA8_ENABLE                 
  #define INTDMA8_ENABLE                  0x00000000u
#endif

// #define INTDMA9_ENABLE                  (IRQ_TABLE_START + 0x00000064u)
#ifndef INTDMA9_ENABLE                 
  #define INTDMA9_ENABLE                  0x00000000u
#endif

// #define INTDMA10_ENABLE                 (IRQ_TABLE_START + 0x00000068u)
#ifndef INTDMA10_ENABLE                
  #define INTDMA10_ENABLE                 0x00000000u
#endif

// #define INTDMA11_ENABLE                 (IRQ_TABLE_START + 0x0000006Cu)
#ifndef INTDMA11_ENABLE                
  #define INTDMA11_ENABLE                 0x00000000u
#endif

// #define INTDMA12_ENABLE                 (IRQ_TABLE_START + 0x00000070u)
#ifndef INTDMA12_ENABLE                
  #define INTDMA12_ENABLE                 0x00000000u
#endif

// #define INTDMA13_ENABLE                 (IRQ_TABLE_START + 0x00000074u)
#ifndef INTDMA13_ENABLE                
  #define INTDMA13_ENABLE                 0x00000000u
#endif

// #define INTDMA14_ENABLE                 (IRQ_TABLE_START + 0x00000078u)
#ifndef INTDMA14_ENABLE                
  #define INTDMA14_ENABLE                 0x00000000u
#endif

// #define INTDMA15_ENABLE                 (IRQ_TABLE_START + 0x0000007Cu)
#ifndef INTDMA15_ENABLE                
  #define INTDMA15_ENABLE                 0x00000000u
#endif

// #define INTP0_ENABLE                    (IRQ_TABLE_START + 0x00000080u)
#ifndef INTP0_ENABLE                   
  #define INTP0_ENABLE                    0x00000000u
#endif

// #define INTP1_ENABLE                    (IRQ_TABLE_START + 0x00000084u)
#ifndef INTP1_ENABLE                   
  #define INTP1_ENABLE                    0x00000000u
#endif

// #define INTP2_ENABLE                    (IRQ_TABLE_START + 0x00000088u)
#ifndef INTP2_ENABLE                   
  #define INTP2_ENABLE                    0x00000000u
#endif

// #define INTP3_ENABLE                    (IRQ_TABLE_START + 0x0000008Cu)
#ifndef INTP3_ENABLE                   
  #define INTP3_ENABLE                    0x00000000u
#endif

// #define INTP4_ENABLE                    (IRQ_TABLE_START + 0x00000090u)
#ifndef INTP4_ENABLE                   
  #define INTP4_ENABLE                    0x00000000u
#endif

// #define INTOTS0OTE_ENABLE               (IRQ_TABLE_START + 0x00000094u)
#ifndef INTOTS0OTE_ENABLE              
  #define INTOTS0OTE_ENABLE               0x00000000u
#endif

// #define INTOTS0OTI_ENABLE               (IRQ_TABLE_START + 0x00000098u)
#ifndef INTOTS0OTI_ENABLE              
  #define INTOTS0OTI_ENABLE               0x00000000u
#endif

// #define INTOTS0OTULI_ENABLE             (IRQ_TABLE_START + 0x0000009Cu)
#ifndef INTOTS0OTULI_ENABLE            
  #define INTOTS0OTULI_ENABLE             0x00000000u
#endif

// #define INTFLXNTU_ENABLE                (IRQ_TABLE_START + 0x000000A0u)
#ifndef INTFLXNTU_ENABLE               
  #define INTFLXNTU_ENABLE                0x00000000u
#endif

// #define INTSTM00_ENABLE                 (IRQ_TABLE_START + 0x000000A4u)
#ifndef INTSTM00_ENABLE                
  #define INTSTM00_ENABLE                 0x00000000u
#endif

// #define INTSTM01_ENABLE                 (IRQ_TABLE_START + 0x000000A8u)
#ifndef INTSTM01_ENABLE                
  #define INTSTM01_ENABLE                 0x00000001u
#endif

// #define INTGTM0ERR_ENABLE               (IRQ_TABLE_START + 0x000000BCu)
#ifndef INTGTM0ERR_ENABLE              
  #define INTGTM0ERR_ENABLE               0x00000000u
#endif

// #define INTGTM0AEI_ENABLE               (IRQ_TABLE_START + 0x000000C0u)
#ifndef INTGTM0AEI_ENABLE              
  #define INTGTM0AEI_ENABLE               0x00000000u
#endif

// #define INTGTM0ARU0_ENABLE              (IRQ_TABLE_START + 0x000000C4u)
#ifndef INTGTM0ARU0_ENABLE             
  #define INTGTM0ARU0_ENABLE              0x00000000u
#endif

// #define INTGTM0ARU1_ENABLE              (IRQ_TABLE_START + 0x000000C8u)
#ifndef INTGTM0ARU1_ENABLE             
  #define INTGTM0ARU1_ENABLE              0x00000000u
#endif

// #define INTGTM0ARU2_ENABLE              (IRQ_TABLE_START + 0x000000CCu)
#ifndef INTGTM0ARU2_ENABLE             
  #define INTGTM0ARU2_ENABLE              0x00000000u
#endif

// #define INTGTM0CMP_ENABLE               (IRQ_TABLE_START + 0x000000D0u)
#ifndef INTGTM0CMP_ENABLE              
  #define INTGTM0CMP_ENABLE               0x00000000u
#endif

// #define INTGTM0TIM00_ENABLE             (IRQ_TABLE_START + 0x000000D4u)
#ifndef INTGTM0TIM00_ENABLE            
  #define INTGTM0TIM00_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM02_ENABLE             (IRQ_TABLE_START + 0x000000D8u)
#ifndef INTGTM0TIM02_ENABLE            
  #define INTGTM0TIM02_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM04_ENABLE             (IRQ_TABLE_START + 0x000000DCu)
#ifndef INTGTM0TIM04_ENABLE            
  #define INTGTM0TIM04_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM06_ENABLE             (IRQ_TABLE_START + 0x000000E0u)
#ifndef INTGTM0TIM06_ENABLE            
  #define INTGTM0TIM06_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM10_ENABLE             (IRQ_TABLE_START + 0x000000E4u)
#ifndef INTGTM0TIM10_ENABLE            
  #define INTGTM0TIM10_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM12_ENABLE             (IRQ_TABLE_START + 0x000000E8u)
#ifndef INTGTM0TIM12_ENABLE            
  #define INTGTM0TIM12_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM14_ENABLE             (IRQ_TABLE_START + 0x000000ECu)
#ifndef INTGTM0TIM14_ENABLE            
  #define INTGTM0TIM14_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM16_ENABLE             (IRQ_TABLE_START + 0x000000F0u)
#ifndef INTGTM0TIM16_ENABLE            
  #define INTGTM0TIM16_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS00_ENABLE             (IRQ_TABLE_START + 0x000000F4u)
#ifndef INTGTM0MCS00_ENABLE            
  #define INTGTM0MCS00_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS02_ENABLE             (IRQ_TABLE_START + 0x000000F8u)
#ifndef INTGTM0MCS02_ENABLE            
  #define INTGTM0MCS02_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS04_ENABLE             (IRQ_TABLE_START + 0x000000FCu)
#ifndef INTGTM0MCS04_ENABLE            
  #define INTGTM0MCS04_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS06_ENABLE             (IRQ_TABLE_START + 0x00000100u)
#ifndef INTGTM0MCS06_ENABLE            
  #define INTGTM0MCS06_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS08_ENABLE             (IRQ_TABLE_START + 0x00000104u)
#ifndef INTGTM0MCS08_ENABLE            
  #define INTGTM0MCS08_ENABLE             0x00000000u
#endif

// #define INTGTM0ATOM00_ENABLE            (IRQ_TABLE_START + 0x00000114u)
#ifndef INTGTM0ATOM00_ENABLE           
  #define INTGTM0ATOM00_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM02_ENABLE            (IRQ_TABLE_START + 0x00000118u)
#ifndef INTGTM0ATOM02_ENABLE           
  #define INTGTM0ATOM02_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM04_ENABLE            (IRQ_TABLE_START + 0x0000011Cu)
#ifndef INTGTM0ATOM04_ENABLE           
  #define INTGTM0ATOM04_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM06_ENABLE            (IRQ_TABLE_START + 0x00000120u)
#ifndef INTGTM0ATOM06_ENABLE           
  #define INTGTM0ATOM06_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM10_ENABLE            (IRQ_TABLE_START + 0x00000124u)
#ifndef INTGTM0ATOM10_ENABLE           
  #define INTGTM0ATOM10_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM12_ENABLE            (IRQ_TABLE_START + 0x00000128u)
#ifndef INTGTM0ATOM12_ENABLE           
  #define INTGTM0ATOM12_ENABLE            0x00000000u
#endif

// #define INTADCF0ERR_ENABLE              (IRQ_TABLE_START + 0x00000140u)
#ifndef INTADCF0ERR_ENABLE             
  #define INTADCF0ERR_ENABLE              0x00000000u
#endif

// #define INTADCF0I0_ENABLE               (IRQ_TABLE_START + 0x00000144u)
#ifndef INTADCF0I0_ENABLE              
  #define INTADCF0I0_ENABLE               0x00000000u
#endif

// #define INTADCF0I1_ENABLE               (IRQ_TABLE_START + 0x00000148u)
#ifndef INTADCF0I1_ENABLE              
  #define INTADCF0I1_ENABLE               0x00000000u
#endif

// #define INTADCF0I2_ENABLE               (IRQ_TABLE_START + 0x0000014Cu)
#ifndef INTADCF0I2_ENABLE              
  #define INTADCF0I2_ENABLE               0x00000000u
#endif

// #define INTADCF0I3_ENABLE               (IRQ_TABLE_START + 0x00000150u)
#ifndef INTADCF0I3_ENABLE              
  #define INTADCF0I3_ENABLE               0x00000000u
#endif

// #define INTADCF0I4_ENABLE               (IRQ_TABLE_START + 0x00000154u)
#ifndef INTADCF0I4_ENABLE              
  #define INTADCF0I4_ENABLE               0x00000000u
#endif

// #define INTCSIH0TIRE_ENABLE             (IRQ_TABLE_START + 0x00000158u)
#ifndef INTCSIH0TIRE_ENABLE            
  #define INTCSIH0TIRE_ENABLE             0x00000000u
#endif

// #define INTCSIH0TIR_ENABLE              (IRQ_TABLE_START + 0x0000015Cu)
#ifndef INTCSIH0TIR_ENABLE             
  #define INTCSIH0TIR_ENABLE              0x00000000u
#endif

// #define INTCSIH0TIC_ENABLE              (IRQ_TABLE_START + 0x00000160u)
#ifndef INTCSIH0TIC_ENABLE             
  #define INTCSIH0TIC_ENABLE              0x00000000u
#endif

// #define INTCSIH0TIJC_ENABLE             (IRQ_TABLE_START + 0x00000164u)
#ifndef INTCSIH0TIJC_ENABLE            
  #define INTCSIH0TIJC_ENABLE             0x00000000u
#endif

// #define INTCSIH1TIRE_ENABLE             (IRQ_TABLE_START + 0x00000168u)
#ifndef INTCSIH1TIRE_ENABLE            
  #define INTCSIH1TIRE_ENABLE             0x00000000u
#endif

// #define INTCSIH1TIR_ENABLE              (IRQ_TABLE_START + 0x0000016Cu)
#ifndef INTCSIH1TIR_ENABLE             
  #define INTCSIH1TIR_ENABLE              0x00000000u
#endif

// #define INTCSIH1TIC_ENABLE              (IRQ_TABLE_START + 0x00000170u)
#ifndef INTCSIH1TIC_ENABLE             
  #define INTCSIH1TIC_ENABLE              0x00000000u
#endif

// #define INTCSIH1TIJC_ENABLE             (IRQ_TABLE_START + 0x00000174u)
#ifndef INTCSIH1TIJC_ENABLE            
  #define INTCSIH1TIJC_ENABLE             0x00000000u
#endif

// #define INTCSIH2TIRE_ENABLE             (IRQ_TABLE_START + 0x00000178u)
#ifndef INTCSIH2TIRE_ENABLE            
  #define INTCSIH2TIRE_ENABLE             0x00000000u
#endif

// #define INTCSIH2TIR_ENABLE              (IRQ_TABLE_START + 0x0000017Cu)
#ifndef INTCSIH2TIR_ENABLE             
  #define INTCSIH2TIR_ENABLE              0x00000000u
#endif

// #define INTCSIH2TIC_ENABLE              (IRQ_TABLE_START + 0x00000180u)
#ifndef INTCSIH2TIC_ENABLE             
  #define INTCSIH2TIC_ENABLE              0x00000000u
#endif

// #define INTCSIH2TIJC_ENABLE             (IRQ_TABLE_START + 0x00000184u)
#ifndef INTCSIH2TIJC_ENABLE            
  #define INTCSIH2TIJC_ENABLE             0x00000000u
#endif

// #define INTCSIH3TIRE_ENABLE             (IRQ_TABLE_START + 0x00000188u)
#ifndef INTCSIH3TIRE_ENABLE            
  #define INTCSIH3TIRE_ENABLE             0x00000000u
#endif

// #define INTCSIH3TIR_ENABLE              (IRQ_TABLE_START + 0x0000018Cu)
#ifndef INTCSIH3TIR_ENABLE             
  #define INTCSIH3TIR_ENABLE              0x00000000u
#endif

// #define INTCSIH3TIC_ENABLE              (IRQ_TABLE_START + 0x00000190u)
#ifndef INTCSIH3TIC_ENABLE             
  #define INTCSIH3TIC_ENABLE              0x00000000u
#endif

// #define INTCSIH3TIJC_ENABLE             (IRQ_TABLE_START + 0x00000194u)
#ifndef INTCSIH3TIJC_ENABLE            
  #define INTCSIH3TIJC_ENABLE             0x00000000u
#endif

// #define INTRLIN30UR2_ENABLE             (IRQ_TABLE_START + 0x00000198u)
#ifndef INTRLIN30UR2_ENABLE            
  #define INTRLIN30UR2_ENABLE             0x00000000u
#endif

// #define INTRLIN30UR1_ENABLE             (IRQ_TABLE_START + 0x0000019Cu)
#ifndef INTRLIN30UR1_ENABLE            
  #define INTRLIN30UR1_ENABLE             0x00000000u
#endif

// #define INTRLIN30UR0_ENABLE             (IRQ_TABLE_START + 0x000001A0u)
#ifndef INTRLIN30UR0_ENABLE            
  #define INTRLIN30UR0_ENABLE             0x00000000u
#endif

// #define INTRLIN31UR2_ENABLE             (IRQ_TABLE_START + 0x000001A4u)
#ifndef INTRLIN31UR2_ENABLE            
  #define INTRLIN31UR2_ENABLE             0x00000000u
#endif

// #define INTRLIN31UR1_ENABLE             (IRQ_TABLE_START + 0x000001A8u)
#ifndef INTRLIN31UR1_ENABLE            
  #define INTRLIN31UR1_ENABLE             0x00000000u
#endif

// #define INTRLIN31UR0_ENABLE             (IRQ_TABLE_START + 0x000001ACu)
#ifndef INTRLIN31UR0_ENABLE            
  #define INTRLIN31UR0_ENABLE             0x00000000u
#endif

// #define INTHSUS0ERR_ENABLE              (IRQ_TABLE_START + 0x000001D0u)
#ifndef INTHSUS0ERR_ENABLE             
  #define INTHSUS0ERR_ENABLE              0x00000000u
#endif

// #define INTHSUS0RE_ENABLE               (IRQ_TABLE_START + 0x000001D4u)
#ifndef INTHSUS0RE_ENABLE              
  #define INTHSUS0RE_ENABLE               0x00000000u
#endif

// #define INTHSUS0TR_ENABLE               (IRQ_TABLE_START + 0x000001D8u)
#ifndef INTHSUS0TR_ENABLE              
  #define INTHSUS0TR_ENABLE               0x00000000u
#endif

// #define INTHSUS1ERR_ENABLE              (IRQ_TABLE_START + 0x000001DCu)
#ifndef INTHSUS1ERR_ENABLE             
  #define INTHSUS1ERR_ENABLE              0x00000000u
#endif

// #define INTHSUS1RE_ENABLE               (IRQ_TABLE_START + 0x000001E0u)
#ifndef INTHSUS1RE_ENABLE              
  #define INTHSUS1RE_ENABLE               0x00000000u
#endif

// #define INTHSUS1TR_ENABLE               (IRQ_TABLE_START + 0x000001E4u)
#ifndef INTHSUS1TR_ENABLE              
  #define INTHSUS1TR_ENABLE               0x00000000u
#endif

// #define INTP5_ENABLE                    (IRQ_TABLE_START + 0x00000200u)
#ifndef INTP5_ENABLE                   
  #define INTP5_ENABLE                    0x00000000u
#endif

// #define INTP6_ENABLE                    (IRQ_TABLE_START + 0x00000204u)
#ifndef INTP6_ENABLE                   
  #define INTP6_ENABLE                    0x00000000u
#endif

// #define INTP7_ENABLE                    (IRQ_TABLE_START + 0x00000208u)
#ifndef INTP7_ENABLE                   
  #define INTP7_ENABLE                    0x00000000u
#endif

// #define INTP9_ENABLE                    (IRQ_TABLE_START + 0x00000210u)
#ifndef INTP9_ENABLE                   
  #define INTP9_ENABLE                    0x00000000u
#endif

// #define INTP10_ENABLE                   (IRQ_TABLE_START + 0x00000214u)
#ifndef INTP10_ENABLE                  
  #define INTP10_ENABLE                   0x00000000u
#endif

// #define INTSTM06_ENABLE                 (IRQ_TABLE_START + 0x0000021Cu)
#ifndef INTSTM06_ENABLE                
  #define INTSTM06_ENABLE                 0x00000000u
#endif

// #define INTSTM07_ENABLE                 (IRQ_TABLE_START + 0x00000220u)
#ifndef INTSTM07_ENABLE                
  #define INTSTM07_ENABLE                 0x00000000u
#endif

// #define INTGTM0TIM01_ENABLE             (IRQ_TABLE_START + 0x00000234u)
#ifndef INTGTM0TIM01_ENABLE            
  #define INTGTM0TIM01_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM03_ENABLE             (IRQ_TABLE_START + 0x00000238u)
#ifndef INTGTM0TIM03_ENABLE            
  #define INTGTM0TIM03_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM05_ENABLE             (IRQ_TABLE_START + 0x0000023Cu)
#ifndef INTGTM0TIM05_ENABLE            
  #define INTGTM0TIM05_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM07_ENABLE             (IRQ_TABLE_START + 0x00000240u)
#ifndef INTGTM0TIM07_ENABLE            
  #define INTGTM0TIM07_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM11_ENABLE             (IRQ_TABLE_START + 0x00000244u)
#ifndef INTGTM0TIM11_ENABLE            
  #define INTGTM0TIM11_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM13_ENABLE             (IRQ_TABLE_START + 0x00000248u)
#ifndef INTGTM0TIM13_ENABLE            
  #define INTGTM0TIM13_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM15_ENABLE             (IRQ_TABLE_START + 0x0000024Cu)
#ifndef INTGTM0TIM15_ENABLE            
  #define INTGTM0TIM15_ENABLE             0x00000000u
#endif

// #define INTGTM0TIM17_ENABLE             (IRQ_TABLE_START + 0x00000250u)
#ifndef INTGTM0TIM17_ENABLE            
  #define INTGTM0TIM17_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS01_ENABLE             (IRQ_TABLE_START + 0x00000254u)
#ifndef INTGTM0MCS01_ENABLE            
  #define INTGTM0MCS01_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS03_ENABLE             (IRQ_TABLE_START + 0x00000258u)
#ifndef INTGTM0MCS03_ENABLE            
  #define INTGTM0MCS03_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS05_ENABLE             (IRQ_TABLE_START + 0x0000025Cu)
#ifndef INTGTM0MCS05_ENABLE            
  #define INTGTM0MCS05_ENABLE             0x00000000u
#endif

// #define INTGTM0MCS07_ENABLE             (IRQ_TABLE_START + 0x00000260u)
#ifndef INTGTM0MCS07_ENABLE            
  #define INTGTM0MCS07_ENABLE             0x00000000u
#endif

// #define INTGTM0ATOM01_ENABLE            (IRQ_TABLE_START + 0x00000270u)
#ifndef INTGTM0ATOM01_ENABLE           
  #define INTGTM0ATOM01_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM03_ENABLE            (IRQ_TABLE_START + 0x00000274u)
#ifndef INTGTM0ATOM03_ENABLE           
  #define INTGTM0ATOM03_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM05_ENABLE            (IRQ_TABLE_START + 0x00000278u)
#ifndef INTGTM0ATOM05_ENABLE           
  #define INTGTM0ATOM05_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM07_ENABLE            (IRQ_TABLE_START + 0x0000027Cu)
#ifndef INTGTM0ATOM07_ENABLE           
  #define INTGTM0ATOM07_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM11_ENABLE            (IRQ_TABLE_START + 0x00000280u)
#ifndef INTGTM0ATOM11_ENABLE           
  #define INTGTM0ATOM11_ENABLE            0x00000000u
#endif

// #define INTGTM0ATOM13_ENABLE            (IRQ_TABLE_START + 0x00000284u)
#ifndef INTGTM0ATOM13_ENABLE           
  #define INTGTM0ATOM13_ENABLE            0x00000000u
#endif

// #define INTADCF1ERR_ENABLE              (IRQ_TABLE_START + 0x00000298u)
#ifndef INTADCF1ERR_ENABLE             
  #define INTADCF1ERR_ENABLE              0x00000000u
#endif

// #define INTADCF1I0_ENABLE               (IRQ_TABLE_START + 0x0000029Cu)
#ifndef INTADCF1I0_ENABLE              
  #define INTADCF1I0_ENABLE               0x00000000u
#endif

// #define INTADCF1I1_ENABLE               (IRQ_TABLE_START + 0x000002A0u)
#ifndef INTADCF1I1_ENABLE              
  #define INTADCF1I1_ENABLE               0x00000000u
#endif

// #define INTADCF1I2_ENABLE               (IRQ_TABLE_START + 0x000002A4u)
#ifndef INTADCF1I2_ENABLE              
  #define INTADCF1I2_ENABLE               0x00000000u
#endif

// #define INTADCF1I3_ENABLE               (IRQ_TABLE_START + 0x000002A8u)
#ifndef INTADCF1I3_ENABLE              
  #define INTADCF1I3_ENABLE               0x00000000u
#endif

// #define INTADCF1I4_ENABLE               (IRQ_TABLE_START + 0x000002ACu)
#ifndef INTADCF1I4_ENABLE              
  #define INTADCF1I4_ENABLE               0x00000000u
#endif

// #define INTMTTCANI0_ENABLE              (IRQ_TABLE_START + 0x000002B0u)
#ifndef INTMTTCANI0_ENABLE             
  #define INTMTTCANI0_ENABLE              0x00000000u
#endif

// #define INTMTTCANI1_ENABLE              (IRQ_TABLE_START + 0x000002B4u)
#ifndef INTMTTCANI1_ENABLE             
  #define INTMTTCANI1_ENABLE              0x00000000u
#endif

// #define INTMTTCANFE_ENABLE              (IRQ_TABLE_START + 0x000002B8u)
#ifndef INTMTTCANFE_ENABLE             
  #define INTMTTCANFE_ENABLE              0x00000000u
#endif

// #define INTMCAN0I0_ENABLE               (IRQ_TABLE_START + 0x000002BCu)
#ifndef INTMCAN0I0_ENABLE              
  #define INTMCAN0I0_ENABLE               0x00000000u
#endif

// #define INTMCAN0I1_ENABLE               (IRQ_TABLE_START + 0x000002C0u)
#ifndef INTMCAN0I1_ENABLE              
  #define INTMCAN0I1_ENABLE               0x00000000u
#endif

// #define INTMCAN0FE_ENABLE               (IRQ_TABLE_START + 0x000002C4u)
#ifndef INTMCAN0FE_ENABLE              
  #define INTMCAN0FE_ENABLE               0x00000000u
#endif

// #define INTMCAN1I0_ENABLE               (IRQ_TABLE_START + 0x000002C8u)
#ifndef INTMCAN1I0_ENABLE              
  #define INTMCAN1I0_ENABLE               0x00000000u
#endif

// #define INTMCAN1I1_ENABLE               (IRQ_TABLE_START + 0x000002CCu)
#ifndef INTMCAN1I1_ENABLE              
  #define INTMCAN1I1_ENABLE               0x00000000u
#endif

// #define INTMCAN1FE_ENABLE               (IRQ_TABLE_START + 0x000002D0u)
#ifndef INTMCAN1FE_ENABLE              
  #define INTMCAN1FE_ENABLE               0x00000000u
#endif

// #define INTETNA0_ENABLE                 (IRQ_TABLE_START + 0x000002E0u)
#ifndef INTETNA0_ENABLE                
  #define INTETNA0_ENABLE                 0x00000000u
#endif

// #define INTFLX0LINE0_ENABLE             (IRQ_TABLE_START + 0x000002E8u)
#ifndef INTFLX0LINE0_ENABLE            
  #define INTFLX0LINE0_ENABLE             0x00000000u
#endif

// #define INTFLX0LINE1_ENABLE             (IRQ_TABLE_START + 0x000002ECu)
#ifndef INTFLX0LINE1_ENABLE            
  #define INTFLX0LINE1_ENABLE             0x00000000u
#endif

// #define INTFLX0TIM0_ENABLE              (IRQ_TABLE_START + 0x000002F0u)
#ifndef INTFLX0TIM0_ENABLE             
  #define INTFLX0TIM0_ENABLE              0x00000000u
#endif

// #define INTFLX0TIM1_ENABLE              (IRQ_TABLE_START + 0x000002F4u)
#ifndef INTFLX0TIM1_ENABLE             
  #define INTFLX0TIM1_ENABLE              0x00000000u
#endif

// #define INTFLX0TIM2_ENABLE              (IRQ_TABLE_START + 0x000002F8u)
#ifndef INTFLX0TIM2_ENABLE             
  #define INTFLX0TIM2_ENABLE              0x00000000u
#endif

// #define INTFLX0FDA_ENABLE               (IRQ_TABLE_START + 0x000002FCu)
#ifndef INTFLX0FDA_ENABLE              
  #define INTFLX0FDA_ENABLE               0x00000000u
#endif

// #define INTFLX0FW_ENABLE                (IRQ_TABLE_START + 0x00000300u)
#ifndef INTFLX0FW_ENABLE               
  #define INTFLX0FW_ENABLE                0x00000000u
#endif

// #define INTFLX0OW_ENABLE                (IRQ_TABLE_START + 0x00000304u)
#ifndef INTFLX0OW_ENABLE               
  #define INTFLX0OW_ENABLE                0x00000000u
#endif

// #define INTFLX0OT_ENABLE                (IRQ_TABLE_START + 0x00000308u)
#ifndef INTFLX0OT_ENABLE               
  #define INTFLX0OT_ENABLE                0x00000000u
#endif

// #define INTFLX0IQF_ENABLE               (IRQ_TABLE_START + 0x0000030Cu)
#ifndef INTFLX0IQF_ENABLE              
  #define INTFLX0IQF_ENABLE               0x00000000u
#endif

// #define INTFLX0IQE_ENABLE               (IRQ_TABLE_START + 0x00000310u)
#ifndef INTFLX0IQE_ENABLE              
  #define INTFLX0IQE_ENABLE               0x00000000u
#endif

// #define INTSENT0SI_ENABLE               (IRQ_TABLE_START + 0x00000340u)
#ifndef INTSENT0SI_ENABLE              
  #define INTSENT0SI_ENABLE               0x00000000u
#endif

// #define INTSENT0RI_ENABLE               (IRQ_TABLE_START + 0x00000344u)
#ifndef INTSENT0RI_ENABLE              
  #define INTSENT0RI_ENABLE               0x00000000u
#endif

// #define INTSENT1SI_ENABLE               (IRQ_TABLE_START + 0x00000348u)
#ifndef INTSENT1SI_ENABLE              
  #define INTSENT1SI_ENABLE               0x00000000u
#endif

// #define INTSENT1RI_ENABLE               (IRQ_TABLE_START + 0x0000034Cu)
#ifndef INTSENT1RI_ENABLE              
  #define INTSENT1RI_ENABLE               0x00000000u
#endif

// #define INTSENT2SI_ENABLE               (IRQ_TABLE_START + 0x00000350u)
#ifndef INTSENT2SI_ENABLE              
  #define INTSENT2SI_ENABLE               0x00000000u
#endif

// #define INTSENT2RI_ENABLE               (IRQ_TABLE_START + 0x00000354u)
#ifndef INTSENT2RI_ENABLE              
  #define INTSENT2RI_ENABLE               0x00000000u
#endif

// #define INTSENT3SI_ENABLE               (IRQ_TABLE_START + 0x00000358u)
#ifndef INTSENT3SI_ENABLE              
  #define INTSENT3SI_ENABLE               0x00000000u
#endif

// #define INTSENT3RI_ENABLE               (IRQ_TABLE_START + 0x0000035Cu)
#ifndef INTSENT3RI_ENABLE              
  #define INTSENT3RI_ENABLE               0x00000000u
#endif

// #define INTSENT4SI_ENABLE               (IRQ_TABLE_START + 0x00000360u)
#ifndef INTSENT4SI_ENABLE              
  #define INTSENT4SI_ENABLE               0x00000000u
#endif

// #define INTSENT4RI_ENABLE               (IRQ_TABLE_START + 0x00000364u)
#ifndef INTSENT4RI_ENABLE              
  #define INTSENT4RI_ENABLE               0x00000000u
#endif

// #define INTSENT5SI_ENABLE               (IRQ_TABLE_START + 0x00000368u)
#ifndef INTSENT5SI_ENABLE              
  #define INTSENT5SI_ENABLE               0x00000000u
#endif

// #define INTSENT5RI_ENABLE               (IRQ_TABLE_START + 0x0000036Cu)
#ifndef INTSENT5RI_ENABLE              
  #define INTSENT5RI_ENABLE               0x00000000u
#endif

// #define INTDTSTC0_ENABLE                (IRQ_TABLE_START + 0x00000390u)
#ifndef INTDTSTC0_ENABLE               
  #define INTDTSTC0_ENABLE                0x00000000u
#endif

// #define INTDTSTC1_ENABLE                (IRQ_TABLE_START + 0x00000394u)
#ifndef INTDTSTC1_ENABLE               
  #define INTDTSTC1_ENABLE                0x00000000u
#endif

// #define INTDTSTC2_ENABLE                (IRQ_TABLE_START + 0x00000398u)
#ifndef INTDTSTC2_ENABLE               
  #define INTDTSTC2_ENABLE                0x00000000u
#endif

// #define INTDTSTC3_ENABLE                (IRQ_TABLE_START + 0x0000039Cu)
#ifndef INTDTSTC3_ENABLE               
  #define INTDTSTC3_ENABLE                0x00000000u
#endif

// #define INTDTSCM0_ENABLE                (IRQ_TABLE_START + 0x000003A0u)
#ifndef INTDTSCM0_ENABLE               
  #define INTDTSCM0_ENABLE                0x00000000u
#endif

// #define INTDTSCM1_ENABLE                (IRQ_TABLE_START + 0x000003A4u)
#ifndef INTDTSCM1_ENABLE               
  #define INTDTSCM1_ENABLE                0x00000000u
#endif

// #define INTDTSCM2_ENABLE                (IRQ_TABLE_START + 0x000003A8u)
#ifndef INTDTSCM2_ENABLE               
  #define INTDTSCM2_ENABLE                0x00000000u
#endif

// #define INTDTSCM3_ENABLE                (IRQ_TABLE_START + 0x000003ACu)
#ifndef INTDTSCM3_ENABLE               
  #define INTDTSCM3_ENABLE                0x00000000u
#endif

// #define INTDCUDEGRADPE_ENABLE           (IRQ_TABLE_START + 0x000003B0u)
#ifndef INTDCUDEGRADPE_ENABLE          
  #define INTDCUDEGRADPE_ENABLE           0x00000000u
#endif

// #define INTFICUIF0CFRQPE_ENABLE         (IRQ_TABLE_START + 0x000003B4u)
#ifndef INTFICUIF0CFRQPE_ENABLE        
  #define INTFICUIF0CFRQPE_ENABLE         0x00000000u
#endif

// #define INTFICUIF0DFRQPE_ENABLE         (IRQ_TABLE_START + 0x000003B8u)
#ifndef INTFICUIF0DFRQPE_ENABLE        
  #define INTFICUIF0DFRQPE_ENABLE         0x00000000u
#endif

// #define INTFICUIF1CFRQPE_ENABLE         (IRQ_TABLE_START + 0x000003BCu)
#ifndef INTFICUIF1CFRQPE_ENABLE        
  #define INTFICUIF1CFRQPE_ENABLE         0x00000000u
#endif

// #define INTDNFA2WUF0_ENABLE             (IRQ_TABLE_START + 0x000003C0u)
#ifndef INTDNFA2WUF0_ENABLE            
  #define INTDNFA2WUF0_ENABLE             0x00000000u
#endif

// #define INTDNFA2WUF1_ENABLE             (IRQ_TABLE_START + 0x000003C4u)
#ifndef INTDNFA2WUF1_ENABLE            
  #define INTDNFA2WUF1_ENABLE             0x00000000u
#endif

// #define INTDNFA3WUF0_ENABLE             (IRQ_TABLE_START + 0x000003C8u)
#ifndef INTDNFA3WUF0_ENABLE            
  #define INTDNFA3WUF0_ENABLE             0x00000000u
#endif

// #define INTDNFA3WUF1_ENABLE             (IRQ_TABLE_START + 0x000003CCu)
#ifndef INTDNFA3WUF1_ENABLE            
  #define INTDNFA3WUF1_ENABLE             0x00000000u
#endif

// #define INTDNFA4WUF0_ENABLE             (IRQ_TABLE_START + 0x000003D0u)
#ifndef INTDNFA4WUF0_ENABLE            
  #define INTDNFA4WUF0_ENABLE             0x00000000u
#endif



#endif /* __R7F701373xABG_IRQ_H */
