function cellInfo = SignalData(varargin) 
% SIGNALDATA returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'Input_Signal', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'LF_Tpms_Value', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RF_Tpms_Value', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LR_Tpms_Value', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RR_Tpms_Value', 1, 'uint32', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
  { ... 
    'Output_Signal', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'LF_Tpms_St', 1, 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RF_Tpms_St', 1, 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'LR_Tpms_St', 1, 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'RR_Tpms_St', 1, 'boolean', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
