/**
*   @file    Os.h
*   @version 1.0.5
*
*   @brief   AUTOSAR OS - Brief file description (one line).
*   @details Detailed file description (can be multiple lines).
*
*   @addtogroup [OS]
*   @{
*/
/*==================================================================================================
*   Project              : AUTOSAR 4.2 MCAL
*   Platform             : ARM
*   Peripheral           : generic
*   Dependencies         : 
*
*   Autosar Version      : 4.2.2
*   Autosar Revision     : ASR_REL_4_2_REV_0002
*   Autosar Conf.Variant :
*   SW Version           : 1.0.5
*   Build Version        : S32K1XX_MCAL_1_0_5_RTM_ASR_REL_4_2_REV_0002_11-Jan-22
*
*   (c) Copyright 2006-2016 Freescale Semiconductor, Inc. 
*       Copyright 2017-2022 NXP
*   All Rights Reserved.
==================================================================================================*/

/*==================================================================================================
==================================================================================================*/

#ifndef OS_H
#define OS_H


#ifdef __cplusplus
extern "C"
{
#endif

#include    "Std_Types.h"     /**< Standard type header - from MCAL  */
#include    "Os_types_public.h"   /**< Autosar OS public types  */
#include    "Os_counter_api.h"

#include    "Os_cfg.h"    /* OS Configuration (generated by SysGen) */

/*==================================================================================================
*                              SOURCE FILE VERSION INFORMATION
==================================================================================================*/


#define OS_VENDOR_ID                    43    /* Freescale AUTOSAR Vendor ID  */
#define OS_MODULE_ID                    0x01           /* OS Module ID                 */

#define OS_AR_RELEASE_MAJOR_VERSION     4   /* Major version number of AUTOSAR specification       */
#define OS_AR_RELEASE_MINOR_VERSION     2   /* Minor version number of AUTOSAR specification       */
#define OS_AR_RELEASE_REVISION_VERSION  2   /* Patch level version number of AUTOSAR specification */

#define OS_SW_MAJOR_VERSION             1   /* Major version number of the implementation   */
#define OS_SW_MINOR_VERSION             0   /* Minor version number of the implementation   */
#define OS_SW_PATCH_VERSION             5   /* Patch level version number of the implementation */

/*==================================================================================================
*                                     FILE VERSION CHECKS
==================================================================================================*/

#ifndef DISABLE_MCAL_INTERMODULE_ASR_CHECK
    /* Check if source file and Std_Types.h header file are of the same Autosar version */
    #if ((OS_AR_RELEASE_MAJOR_VERSION != STD_AR_RELEASE_MAJOR_VERSION) || \
         (OS_AR_RELEASE_MINOR_VERSION != STD_AR_RELEASE_MINOR_VERSION))
        #error "AutoSar Version Numbers of Os.h and Std_Types.h are different"
    #endif
#endif
/* Check current file version with Os_types_public.h file */
#if (OS_VENDOR_ID != OS_TYPE_PUBLIC_VENDOR_ID)
    #error "Os.h and Os_types_public.h have different vendor ids"
#endif
#if ((OS_AR_RELEASE_MAJOR_VERSION    != OS_TYPE_PUBLIC_AR_RELEASE_MAJOR_VERSION) || \
     (OS_AR_RELEASE_MINOR_VERSION    != OS_TYPE_PUBLIC_AR_RELEASE_MINOR_VERSION) || \
     (OS_AR_RELEASE_REVISION_VERSION != OS_TYPE_PUBLIC_AR_RELEASE_REVISION_VERSION))
    #error "AutoSar Version Numbers of Os.h and Os_types_public.h are different"
#endif
#if ((OS_SW_MAJOR_VERSION != OS_TYPE_PUBLIC_SW_MAJOR_VERSION) || \
     (OS_SW_MINOR_VERSION != OS_TYPE_PUBLIC_SW_MINOR_VERSION) || \
     (OS_SW_PATCH_VERSION != OS_TYPE_PUBLIC_SW_PATCH_VERSION))
    #error "Software Version Numbers of Os.h and Os_types_public.h are different"
#endif


/* Check current file version with Os_counter_api.h file */
#if (OS_VENDOR_ID != OS_COUNTER_API_VENDOR_ID)
    #error "Os.h and Os_counter_api.h have different vendor ids"
#endif
#if ((OS_AR_RELEASE_MAJOR_VERSION    != OS_COUNTER_API_AR_RELEASE_MAJOR_VERSION) || \
     (OS_AR_RELEASE_MINOR_VERSION    != OS_COUNTER_API_AR_RELEASE_MINOR_VERSION) || \
     (OS_AR_RELEASE_REVISION_VERSION != OS_COUNTER_API_AR_RELEASE_REVISION_VERSION))
    #error "AutoSar Version Numbers of Os.h and Os_counter_api.h are different"
#endif
#if ((OS_SW_MAJOR_VERSION != OS_COUNTER_API_SW_MAJOR_VERSION) || \
     (OS_SW_MINOR_VERSION != OS_COUNTER_API_SW_MINOR_VERSION) || \
     (OS_SW_PATCH_VERSION != OS_COUNTER_API_SW_PATCH_VERSION))
    #error "Software Version Numbers of Os.h and Os_counter_api.h are different"
#endif


/* Check current file version with Os_cfg.h file */
#if (OS_VENDOR_ID != OS_CFG_VENDOR_ID)
    #error "Os.h and Os_cfg.h have different vendor ids"
#endif
#if ((OS_AR_RELEASE_MAJOR_VERSION    != OS_CFG_AR_RELEASE_MAJOR_VERSION_H) || \
     (OS_AR_RELEASE_MINOR_VERSION    != OS_CFG_AR_RELEASE_MINOR_VERSION_H) || \
     (OS_AR_RELEASE_REVISION_VERSION != OS_CFG_AR_RELEASE_REVISION_VERSION_H))
    #error "AutoSar Version Numbers of Os.h and Os_cfg.h are different"
#endif
#if ((OS_SW_MAJOR_VERSION != OS_CFG_SW_MAJOR_VERSION_H) || \
     (OS_SW_MINOR_VERSION != OS_CFG_SW_MINOR_VERSION_H) || \
     (OS_SW_PATCH_VERSION != OS_CFG_SW_PATCH_VERSION_H))
    #error "Software Version Numbers of Os.h and Os_cfg.h are different"
#endif






#ifdef __cplusplus
}
#endif



#endif /*OS_H*/

/** @} */

